server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
girl:
  cupSize: B
  age: 18
  msg: 按计划但是看见

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sport?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: lgm123
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8

#  配置redis连接信息
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
##    timeout: 10
#    jedis:
#      pool:
#        # 最大空闲连接
#        max-idle: 8
#        # 最小空闲链接
#        min-idle: 0
#        # 最大连接数（负数表示没有限制）
#        max-active: 8
#        # 最大阻塞等待时间（负数表示没有限制）
#        max-wait: 0
#      # 链接超时时间（毫秒）
#      timeout: 50



  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

content: "cupSize: ${cupSize},age:${age}"

swagger:
  enabled: true
  title: 21su-API
  description: 工塑之家API文档
  base-package:  com.example.springttest.controller
  base-path: /**
  exclude-path: /error
mybatis:
  mapper-locations: classpath:com/example/springboottest/mapper/*.xml

